### ISSUE TITLE
Kakao 소셜 로그인 보강 (소셜 회원가입까지?) + 로직 이해하기 위한 주석달기

### ISSUE THREAD

**Issue by Jonggae** [JisooPyo/KP3C-backoffice-project#28]
우선 소셜로그인을 할때 뭐가 더 필요한지 알아보겠습니다.

다른 분들이 만드시는 것들이 필요하다면 기다려야겠죠.. 다들 열심히 하셔서 저도 도움이 많이 되네요.

테스트도 해보고싶고 해서 우선 로직 이해하는 것부터 해보겠습니다. 설명할 수 있게 주석도 달아볼게요..

프론트를 간단하게 만들어볼까하는데 이건 될지 안될지 모르겠습니다! (JS에서 망할것 같아서 ㅋㅋ/ 안할 수도 있음)

**Comment by JisooPyo** [comment]
우워 프론트.. 화이팅입니다!!!

**Comment by Jonggae** [comment]
프론트는.. 그냥 목표입니다............ ㅜㅜ
