### ISSUE TITLE
Admin(관리자) 기능: SNS 백오피스에 대해

### ISSUE THREAD

**Issue by jungeun5-choi** [JisooPyo/KP3C-backoffice-project#30]
예시에 적혀있던 관리자 권한

### 회원 관리
1. 회원 조회하기
2. 사이트 회원 정보 수정하기
3. 사이트 회원 삭제하기
4. 회원 운영진으로 승격
5. 회원 차단하기

### 게시글 관리
1. 공지글 등록하기
2. 모든 게시글 수정하기
3. 모든 게시글 삭제하기

**Comment by eunb1** [comment]
댓글 관리와 로그 모니터링이 있을 수 있겠습니다...
더 찾아볼게요!

참고 링크 https://guide.worksmobile.com/kr/admin/admin-guide/overview/

**Comment by jungeun5-choi** [comment]
헐 감사해요 참고해볼게요!

**Comment by JisooPyo** [comment]
> 댓글 관리와 로그 모니터링이 있을 수 있겠습니다... 더 찾아볼게요!
> 
> 참고 링크 https://guide.worksmobile.com/kr/admin/admin-guide/overview/

머시따 은비님~~ 역시 고수!!!!

**Comment by jungeun5-choi** [comment]
## 1) 알고리즘에서
1. 메인 피드에서 몇개의 글이 표시되어야하는지 (기본값?)
2. User SNS 사용자들 정보를 리스트업 관리
3. 검색
4. 계정 차단
    - 글 관리 -> 불량 게시글 필터링?
    - 유저 관리 -> 가짜계정

## 2) 추가적으로
1. 유저가 실제로 얼마나 접속하는지 -> 사람당 얼마나
2. 한 달 간 한 번이라도 들어온 사람의 수
3. 유저가 평균적으로 올리는 글 수
4. 통계

## 3) 큰 틀은 세 가지정도
1. 글 관리
    - 글 리스트
2. 유저 관리
    - 유저 리스트
3. 피드 관리

**Comment by jungeun5-choi** [comment]
여기서 현 단계에서 해볼 수 있을만한? 것들은
1. 글 관리
    - 글 전체 리스트업해서 관리?
2. 유저 관리
    - User SNS 사용자들 정보를 리스트업 관리
    - 계정 차단
    - (모니터링)
        - 유저가 실제로 얼마나 접속하는지 -> 사람당 얼마나 
        - 한 달 간 한 번이라도 들어온 사람의 수
        - 유저가 평균적으로 올리는 글 수
3. 피드 관리
    - 메인 피드에서 몇 개의 글이 표시되어야하는지

**Comment by jungeun5-choi** [comment]
모니터링용 컨트롤러를 만들까? 싶기도 하네요!!
모니터링하려면 User 엔티티에 이거저거 추가해야할 것도 같구요!

**Comment by JisooPyo** [comment]
다 구현할 수 있으면 정말 좋겠네요!! 그럼 진짜진짜로 배포해서 쓰고 싶을 거 같아요..
