### ISSUE TITLE
SNS상에서는 댓글=포스트 역할을 하기도 하는데 어떤 식으로 구현을 해야 할 지 고민이에요!

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/KP3C-backoffice-project#34]
트위터를 보면
글 > 글 > 글 > 글 > 글  이런식으로 답글이 달리는데 이런 형식은 어떻게 구현해야 할까요?
기존에 했던 Post 와 Comment 식으로 하려니 sns가 아니라 블로그의 느낌이 나서 어떻게 구현해야 할지 잘 모르겠네요..

**Comment by JisooPyo** [comment]
@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_comment_id")
	private Comment parentComment;
	
를 Comment entity에 넣어서 해보려고 하는데 어떻게 생각하시나요..!

**Comment by eunb1** [comment]
Threaded comments 또는 nested comments 로 구글링해보면 지수님 말씀처럼 부모자식 구조의 트리나 링크드리스트를 많이 활용하는것 같습니다 좋은 자료 찾으면 공유 드릴게요! 여러모로 쉽지 않아 보이네요..🥲

**Comment by jungeun5-choi** [comment]
단순하게 Dto를 생각해보면
```
{
"content":"content",
"commentList":[
    {
    "content":"content",
    "commentList":[
        {
        "content":"content",
        "commentList":[]
        },
        ... ]
    },
    ... ]
}
```
이런 구조가 될테니 Post 클래스마다 LinkedList를 품고 있는 형태로 하면 괜찮을 것 같네요! 이런 경우엔 Post ERD가 어떻게 구성될까요? 🤔

**Comment by JisooPyo** [comment]
> Threaded comments 또는 nested comments 로 구글링해보면 지수님 말씀처럼 부모자식 구조의 트리나 링크드리스트를 많이 활용하는것 같습니다 좋은 자료 찾으면 공유 드릴게요! 여러모로 쉽지 않아 보이네요..🥲

감사합니다!! 저도 조금 더 구글링해보겠습니다!

**Comment by JisooPyo** [comment]
> 단순하게 Dto를 생각해보면
> 
> ```
> {
> "content":"content",
> "commentList":[
>     {
>     "content":"content",
>     "commentList":[
>         {
>         "content":"content",
>         "commentList":[]
>         },
>         ...
>     },
>     ...
> }
> ```
> 
> 이런 구조가 될테니 Post 클래스마다 LinkedList를 품고 있는 형태로 하면 괜찮을 것 같네요! 이런 경우엔 Post ERD가 어떻게 구성될까요? 🤔

저도 뭔가 언뜻 느낌만 있고 구현을 어떻게 해야 할 지 감이 잘 안 잡히네요! 한 번 해보겠습니다! Comment는 당연히 전이랑 똑같을 줄 알았는데 생각해보니까 조금 달라져서 생각할게 많아졌네요 ㅋㅋ

**Comment by jungeun5-choi** [comment]
- [게시판 댓글, 대댓글(무한댓글) 로직](https://velog.io/@yoho98/%EA%B2%8C%EC%8B%9C%EA%B8%80-%EB%8C%93%EA%B8%80-%EB%8C%80%EB%8C%93%EA%B8%80%EB%AC%B4%ED%95%9C%EB%8C%93%EA%B8%80-%EB%A1%9C%EC%A7%81)
- [스프링부트 JPA querydsl 대댓글(계층형 댓글) 기능 구현](https://kukekyakya.tistory.com/9)

이렇게 두 개 참고하기 괜찮은 거 같아요! 둘 공통점은 Comment가 `parent`(위) 정보와 `children`(아래) 정보를 저장한다는 것 같습니다
