### ISSUE TITLE
User 클래스 API에 대해서(follow, 소셜 로그인, 회원가입, 로그인)

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/KP3C-backoffice-project#39]
현재

```java
http.authorizeHttpRequests((authorizeHttpRequests) ->
	authorizeHttpRequests
			.requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll() // resources 접근 허용 설정
			.requestMatchers("/kp3c/user/**").permitAll()
			.anyRequest().authenticated() // 그 외 모든 요청 인증처리
		);
```

로 되어 있어서 '/api/user/'로 시작하는 요청 모두 접근 허가가 되어 있는 상태인데

```java
@RequestMapping("/kp3c/user")
public class UserController {

    ...

    @GetMapping("/{username}/followers")
        public ResponseEntity<List<ProfileDto>> getFollowers(@PathVariable String username) {
            ...
        }
}
```

로 되어 있어서 팔로워의 목록을 보여주는 메서드, 팔로잉의 목록을 보여주는 메서드, 팔로우를 하는 메서드, 팔로우을 취소하는 메서드
가 인증, 인가를 받지 않은채 통과가 되고 있습니다.

이를 해결하려면

1. 팔로워, 팔로잉 메서드의 api를 바꿔주거나
2. 회원가입, 로그인, 소셜 로그인 api를 바꿔주거나
3. requestMapping()에서 다른 조건을 찾아보거나

중에 선택해야 할 거 같습니다!
어떻게 하는게 좋을까요?

**Comment by jungeun5-choi** [comment]
지난 주차 팀프로젝트에서 api 건으로 피드백을 받았었는데
회원가입, 로그인은 아직 가입된 유저가 아니라서 도메인에 `/user` 붙이는게 부적절하다는? 얘기를 들었었어요!
`/user` 대신 `/auth` 같은 걸로 바꾸는 건 어떤가요?

트위터를 가입해서 보고 왔는데 트위터는
`twitter.com/{username}`
`twitter.com/{username}/following`
이런 식으로 하는 것 같아서 이것도 나쁘지 않아 보여요!

**Comment by JisooPyo** [comment]
앗 오~~ auth!! 좋은 의견인 것 같습니다!! 오와 지챠 너무 감사합니다 ㅠㅠ
팔로워와 팔로잉의 api도 참고해서 은비님과 의견 조율하여 변경해보겠습니다!! 의견 정말 좋아요!! 정은님 최고!!

**Comment by JisooPyo** [comment]
```java
/user/signup
/user/login
```
요청을 아예 명시하여 패스시키기로!
