### ISSUE TITLE
Redis를 활용한 JWT 토큰 관리

### ISSUE THREAD

**Issue by eunb1** [JisooPyo/KP3C-backoffice-project#44]
카카오 소셜 로그인 로직 톺아보고 Redis 사용해서 jwt access token, refresh token 구현해보겠습니다.
+) 시간이 된다면 기타 플랫폼 (구글, 깃허브 등) 소셜 로그인까지 도전해볼게요!

Redis 공부하고 @jungeun5-choi 님께 의견 공유 예정.

**Comment by jungeun5-choi** [comment]
파이팅!!!!!!!!!!! 🔥

**Comment by jungeun5-choi** [comment]
jpa connection -> redis 연결이 쉬움
(redis는 따지고보면 DB가 아니라서)

redis랑 session 관리는 찰떡이다!
- 예를 들면 토큰 만료시간 조절에 자주 쓰임
- redis는 인메모리DB이기 때문에 저장하는 데이터 크기가 큰 것은 좋지 않다
    - 데이터 저장 시 고려할 점
        - 엔티티 자체는 저장x
        - 필요한 데이터만 저장하는게 바람직하다
        - redis를 사용하는 이유는 DB 부하를 줄이기 위해서(정보를 DB를 통해서 가져오지 않아도 되도록)
        - 리프레시 전략? TTL: time to leave을 제대로 명시

**redis 서버와 AWS 웹서버 배포를 동시에 진행하는 경우**
- AWS로 웹서버 배포시 보안 설정 등 고려해야함
    - redis 서버라는 또 다른 서버에서 데이터를 가져오는 것이기 때문에
- AWS에서 redis르 띄우는 두 가지 방법
    1. redis - elasticache 사용하는 방법
    2. Amazon EC2 인스턴스 (싼 거) 하나 만들어서 이 안에서 redis를 띄우는 방법

**Comment by JisooPyo** [comment]
화이팅!!!!
