### ISSUE TITLE
Redis 도입해보기

### ISSUE THREAD

**Issue by jungeun5-choi** [JisooPyo/KP3C-backoffice-project#47]
jpa connection -> redis 연결이 쉬움
(redis는 따지고보면 DB가 아니라서)

redis와 session 관리는 찰떡이다!
- 예를 들면 토큰 만료시간 조절에 자주 쓰임
- redis는 인메모리DB이기 때문에 저장하는 데이터 크기가 큰 것은 좋지 않다
    - 데이터 저장 시 고려할 점
        - 엔티티 자체는 저장x
            - > redis class에 엔티티 자체를 저장하면 stackoverflowError가 난다고 함
        - 필요한 데이터만 저장하는게 바람직하다
        - redis를 사용하는 이유는 DB 부하를 줄이기 위해서(정보를 DB를 통해서 가져오지 않아도 되도록)
        - 리프레시 전략? TTL: time to leave을 제대로 명시

**redis 서버와 AWS 웹서버 배포를 동시에 진행하는 경우**
- 서로 다른 브랜치에서 각각의 배포 작업을 하고 merge해도 문제는 없을 것
    - 물론 아래와 같은 문제는 고려해보아야한다 (기본적)
- AWS로 웹서버 배포시 보안 설정 등 고려해야함
    - redis 서버라는 또 다른 서버에서 데이터를 가져오는 것이기 때문에
- **AWS에서 redis를 띄우는 두 가지 방법**
    1. redis - elasticache 사용하는 방법
    2. Amazon EC2 인스턴스 (싼 걸로...) 하나 만들어서 이 안에서 redis를 띄우는 방법

**Comment by jungeun5-choi** [comment]
## Redis 관련 공식 문서
- [redis.io](https://redis.io/docs/) (redis 공식 doc)
- [Spring Data Redis 3.0.5](https://docs.spring.io/spring-data/redis/docs/3.0.5/reference/html/)
    - 버전 다르면 문서 수정 예정
    - [spring-data-redis](https://github.com/spring-projects/spring-data-redis) repository
- AWS > aws-documentation > Amazon ElastiCache > [지원되는 ElastiCache for Redis 버전](https://docs.aws.amazon.com/ko_kr/AmazonElastiCache/latest/red-ug/supported-engine-versions.html)

## Redis에 대한 참고 자료
- [[10분 테코톡] 디디의 Redis](https://youtu.be/Gimv7hroM8A)
- [[NHN FORWARD 2021] Redis 야무지게 사용하기](https://youtu.be/92NizoBL4uA)
- [Redis Tutorial for Beginners](https://www.youtube.com/playlist?list=PLS1QulWo1RIYZZxQdap7Sd0ARKFI-XVsd) (영문)
- [learn-redis](https://github.com/dwyl/learn-redis) (redis 자습서.. 좀 오래됨)
- [redisGate](http://www.redisgate.com/redis/)

**Comment by jungeun5-choi** [comment]
## Redis 기본 세팅
- [Windows 10 환경에 Redis 설치해보기](https://oingdaddy.tistory.com/239)
- [Springboot + Redis 연동하는 초간단 샘플 만들어보기](https://oingdaddy.tistory.com/239)
- [[Redis] 비밀번호 설정](https://passwd.tistory.com/entry/Redis-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8-%EC%84%A4%EC%A0%95)

#### build.gradle
```
dependencies {
    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
}
```

#### application.properties
```
#redis
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.password={requirepass}
```

#### WebSecurityConfig 
```java
.requestMatchers("/redis/**").permitAll() // redis test용 임시 허가
```

### 테스트 결과
![image](https://github.com/JisooPyo/KP3C-backoffice-project/assets/119802267/fd00f91f-8815-48a5-95c4-716e8fe7cd95)

**Comment by jungeun5-choi** [comment]
### WebSecurityConfig 
```java
.requestMatchers("/redis/**").permitAll() // redis용 임시 허가
```

### 테스트 결과
![image](https://github.com/JisooPyo/KP3C-backoffice-project/assets/119802267/fd00f91f-8815-48a5-95c4-716e8fe7cd95)

**Comment by JisooPyo** [comment]
기록 잘하시는거 진짜 배워야겠네요 헉소리나네.. 멋있습니다

**Comment by jungeun5-choi** [comment]
## 문제점 1
**redis에 entity 자체를 저장하는 것은 비효율적이다.**
- 그렇다면 redis용 새로운 entity를 만들어야하나?
- 만든다면 어떻게? ↓

## 해결(하려고 시도하는) 과정

1. 저장하려는 정보를 명확히 할 것
    - 내가 저장하려는 정보는 무엇인가? 

2. 피드를 불러오려면 #51 
    - 피드를 불러오는 조건? → 나 + 내가 팔로우한 사람
        - 나(=로그인 한 회원)와 내가 팔로우한 사람의 id가 필요
        - 작성한 게시글의 id 필요

3. 그럼 redis에 내가 팔로우한 사람들의 id를 저장하자

4. data type은 뭐가 좋을까? [개발자를 위한 레디스 튜토리얼 01](https://medium.com/garimoo/%EA%B0%9C%EB%B0%9C%EC%9E%90%EB%A5%BC-%EC%9C%84%ED%95%9C-%EB%A0%88%EB%94%94%EC%8A%A4-%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC-01-92aaa24ca8cc)
    - List / [Lists 명령어 리스트](http://www.redisgate.com/redis/command/lists.php)
        - Lists는 key와 value가 일 대 다 관계
        - Blocking 기능을 이용해 Event Queue로 사용할 수 있음

## 참고
- **[소셜 네트워킹 서비스 Twitter의 Redis 적용 사례](https://droomii.tistory.com/m/18)**
    
    ![image](https://github.com/JisooPyo/KP3C-backoffice-project/assets/119802267/e53c481f-6268-4aa8-ad45-b418605dab09)

    - 트윗의 사례
        - 타임라인을 보여주기 위해 저장하는 정보
            -  작성한 트윗 ID와 트윗 작성자의 ID
        - 순서?
            1. 내가 트윗을 작성
            2. 내 팔로워들의 타임라인 캐시에 내가 작성한 트윗 ID를 추가
            3. 내 팔로워들이 자신들의 타임라인에 들어가면, 타임라인 캐시에 있는 나의 트윗 ID로 DB에 요청 

- **[[Redis에 대하여] 2. 캐싱 전략](https://velog.io/@oroko/Redis%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC2-%EC%BA%90%EC%8B%B1-%EC%A0%84%EB%9E%B5)**
    - 이웃 간의 '좋아요' 수를 캐싱을 시도한 사례
        1. 좋아요 정보는 캐시에만 쓰고, 캐시에서만 읽는다
        2. 주기적으로 캐시 → DB 반영<br><br>

    > MySQL만 사용했다면 각 게시물ID-프로필ID의 쌍을 모두 저장하고 이를 사용하지만, Redis를 사용해서 게시물ID에 대해서 프로필ID의 Set을 저장하면 된다. 

- **[[NHN FORWARD 2021] Redis 야무지게 사용하기](https://youtu.be/92NizoBL4uA)**
    - Messaging(= 비동기 대화)의 예제에서 data type으로 List와 Stream을 보여줌
        - 트위터 타임라인에서 RPUSHX 커맨드를 사용한다고 한다
            - 트위터를 자주 사용하는 유저의 TL에만 새로운 데이터를 미리 캐싱

**Comment by JisooPyo** [comment]
아앗 entity로 들어가는 구조가 아닌가보군요

**Comment by jungeun5-choi** [comment]
> 아앗 entity로 들어가는 구조가 아닌가보군요

mysql이랑 연결할 때 entity 자체를 직렬화(serialize)해서 저장하는 방법이 보편적인 거 같은데 그렇게 하면 entity 자체를 저장하게 되는게 아닌가 하는 생각이 들더라고요 (제가 이해를 잘못한 걸 수도 잇음...)

그래서 일단 이 방식으로 해서 성공하면 새롭게 리팩터링을 할지, 아니면 처음부터 꺾어서 갈지...를 고민하고 있어요 ㅋㅋ

**Comment by JisooPyo** [comment]
그 redis 고수 튜터님한테 슬랙으로 dm을 보내서 조언을 구해보는 건 어떠신가요!

**Comment by jungeun5-choi** [comment]
> 그 redis 고수 튜터님한테 슬랙으로 dm을 보내서 조언을 구해보는 건 어떠신가요!

자료 좀 더 찾아보고 답 없으면 저녁 시간에 한 번 보내봐야겠어요!! 감사해요 ㅎㅎ

**Comment by jungeun5-choi** [comment]
- [Redis를 사용한 메시징](https://spring.io/guides/gs/messaging-redis/)
- [트위터 팔로워 타임라인 시스템 분석](https://americanopeople.tistory.com/328)
- [[Redis] Redis 환경 간단하게 구축하기](https://gogo-jjm.tistory.com/35)
- [[Springboot] '최근 읽은 글' Dto로 Redis에 저장하고 조회하기 AtoZ](https://tape22.tistory.com/25)

**Comment by jungeun5-choi** [comment]
## 타임라인(피드) 1 : 
> 내가 작성한 글을 redis에 저장하기

### [풀리퀘스트](https://github.com/JisooPyo/KP3C-backoffice-project/pull/52#issue-1814578107)

**Comment by jungeun5-choi** [comment]
## 문제점 2
**id만 저장하면 결국 데이터를 받아올 때는 DB를 조회하게 된다**
- id를 저장하는 것은 메모리를 덜 쓰기 때문에 좋은 방법이지만, 필요한 데이터를 받아올 때는 결국 id를 통해서 DB를 받아오게 된다.
    - 실제로 위의 `RedisTimelineService.getTimelinePosts`에서는 `PostRepository`를 참조하고 있다...
- 그러면 redis를 쓰는 의미가 없어지지 않나?

### value는 Dto를 사용해서 저장해보자
[[Springboot] '최근 읽은 글' Dto로 Redis에 저장하고 조회하기 AtoZ](https://tape22.tistory.com/25)
- redis에 저장할 dto를 최소한의 구조로 만들어서 value에 넣어주면 DB를 조회하지 않아도 된다.
- dto에 들어갈 정보 (예상)
    - id / username / nickname / content / created_at

**Comment by jungeun5-choi** [comment]
## 타임라인(피드) 2:
> - value 값에 id 대신 Dto 저장

### [풀리퀘스트](https://github.com/JisooPyo/KP3C-backoffice-project/pull/52#issuecomment-1644404580)

**Comment by jungeun5-choi** [comment]
## redis-cli 데이터 조회 명령어

1. **redis 캐시 메모리 접근**
    ```
    > auth {password}
    > auth abcde
    ```
2. **전체 key 확인**
    ```
    > keys *
    ```
3. **key를 활용해 value 확인하는 법**
    ```
    > LRANGE {key} {start_index} {end_index}
    > LRANGE 1 0 5
    ```
4. **redis에서 데이터 전체 삭제**
    ```
    > flushall
    ```

**Comment by jungeun5-choi** [comment]
## 문제점 3
**타임라인은 어떻게 만들어야하는가?**
> Feed => 내가 쓴 글, 내가 팔로우한 회원이 쓴 글 표시

1. DB에 정보를 저장하는 경우
    - 요청이 들어올 때 DB만 보여주면 됨
2. Redis를 사용해 캐시에 정보를 저장하는 경우
    - 데이터를 갱신하거나 DB와 싱크를 맞춰야할 때 - 스케줄러를 추가해야함
        - 튜터님 曰: 배보다 배꼽이 더 커지는 것 아닌가?
    - 그리고 시간도 없음!!

### 타임라인(피드)는 DB로 구현하는 것을 최우선으로...
- 구현한 다음에 시간이 남으면 Redis를 활용해 캐시에 올려서 고도화 해보자!

## 문제점 4
**Feed(피드, 타임라인) 엔티티는 어떤 정보를 가지고 있어야 하는가?**
> Feed => 내가 쓴 글, 내가 팔로우한 회원이 쓴 글 표시

### 생각하고 있는 순서...
1. 회원 생성 → Feed 생성 (`user_id` value = `feed_id` value)
    - 이러면 Feed 주인 (= user_id)을 따로 저장하지 않아도 된다.
    - 그래도 안전하려면 저장하는게...

2. 누군가를 팔로우 → 팔로우한 회원의 Post를 `List<Post>`에 추가
    - List<Post> = 표시할 글 전체
        - 무한정 늘릴 수는 없으니 개수 제한을 두거나...
        - 순서 정렬은 Paging을 사용 -> `created_at`이나 `post_id`를 기준으로

3. 나 혹은 다른 회원이 글을 작성
    - Post DB에 저장
    - Redis Cache에도 저장
    - Feed DB에는 언제 저장될까?
        1. 내가 누군가를 팔로우 했을 때
        2. 내가 글을 썼을 때

**Comment by jungeun5-choi** [comment]
## 오늘의 주제: 작성한 게시글 캐싱하기
